### PR TITLE
Show infoWindow on specific encounter when specified in querystring

### PR DESCRIPTION
**Pull request by hokiepokedad**
If you have any alerts displaying to a user of a specific pokemon, you would usually link to a google maps link.  For those of you that want to link back to your map in those alerts and have the infoWindow open upon entry of the map, you can include the encounter_id in the url in the following format:

http(s)://host_name/?lat=##.###&lon=-##.###&encId=#########&zoom=16

The "encId" querystring parameter is used to pass the encounter id to the map.  

Note:  This is to be used in conjunction with passing the lat and lon.  Also, if a user has the alerted pokemon hidden on the map, this will show the particular pokemon associated with the encounter id, regardless of user setting.

### CODE REVIEW

**Comment by CalamityJames** [comment]
I like this PR and I've wanted to offer this option myself. I will give it some testing when I have a bit of time later this week

**Comment by cptmedic** [comment]
Hey, not sure if you are aware. But I believe it is now broken since the branch change. It will pull up the info window if the pokemon is not excluded, but won't if it is excluded.

**Comment by CalamityJames** [comment]
I have managed to get this functioning on the `develop` branch, finally.

There is one current problem with it, which may be related to changes with how filters work:

Any Pokémon hidden from your filter will not appear, even with an `encId` parameter, so this will need further study/work.

**Comment by cptmedic** [comment]
it works <3

**Comment by cptmedic** [comment]
@CalamityJames Hey one thing I noticed was that if you set a minimum IV or level, or both. The encid does not override those settings. Just wanted to report that.

**Comment by hammydown4325** [comment]
@captainmedic I made some adjustments to this here: https://github.com/iroken222/PMSF/tree/encountered

Waiting for @CalamityJames to get to a place where he can look it over and merge it into the PR for me.

**Comment by Glennmen** [comment]
@captainmedic Can you test last commit, thanks!

**Pull request merged**
