### PR TITLE
Potential fix for raid bug vanilla RM and Sloppy's RM fork.

### PR DESCRIPTION
**Pull request by Harmmmm**
Potential fix for the bug that causes raids that are ended to stay on the map on vanilla RM and sloppy's RM.
(Needs testing!)

Stuff that is changed:

- Fixed type on line 1002 for Sloppy's fork
- Added prepared statement on line 854 for lastScanned for vanilla RM
- Changed date format to default format

### CODE REVIEW

**Review by CalamityJames — APPROVED** [review]
This all looks good to me, nice work finding the prepared statement I missed too!

**Comment by h0us3cat** [comment]
I installed this but does not change much, unless i did it wrong.
Running stock rocketmap.

**Comment by friscoMad** [comment]
Still testing in RM but at least fixes the same as #23 and I see a drop in 1/2 the process time and it sends 1/100 of data so that already are great news.

**Comment by friscoMad** [comment]
Raids stay in map unless you move them out and in of view but that is how stock RM UI works anyway so I am not sure if that's the fix.
Anyway just for the db load, data usage and responsiveness this or #23 should be merged.

**Pull request merged**
