### PR TITLE
add locale moves

### PR DESCRIPTION
**Pull request by M4d40**
add moves for different languages (thanks to the multilanguage support).

* moves for following languages added: de, it, jp, ko, pt_br, sp, zh_tw
* also renamed 'ja' to 'jp' to be more ISO conform

### CODE REVIEW

**Review by CalamityJames — APPROVED** [review]
No idea if the translations are correct, but the code looks sound to me!

**Comment by Glennmen** [comment]
I know that chaning `ja` to`jp` is the most logical move, but however the internet is not logical...
This works: https://pokemon.gameinfo.io/ja/pokemon/1-bulbasaur
This displays default english: https://pokemon.gameinfo.io/jp/pokemon/1-bulbasaur

However after checking `pt_br` and `zh_tw` also don't work because the site uses `-`.

**Comment by M4d40** [comment]
@Glennmen 
So the question is: are we going against ISO and worldwide standards because this one site is not using them, or not?

(If we want both, the site and the normal standards, we could do if/else to overwrite the language variable for the gameinfo site, where it is against the standards:

https://github.com/Glennmen/PMSF/blob/develop/static/js/map.js#L479
https://github.com/Glennmen/PMSF/blob/develop/static/js/stats.js#L51

Those are the lines where the site is linked with the language.)

**Comment by Glennmen** [comment]
@M4d40 You are right, we should follow ISO standards.
I will merge this later and after that I will work something out to make better language compatibility for that site.

**Pull request merged**
