### PR TITLE
[fix] Spawnpoint Timers

### LINKED ISSUE #38: [bug] Spawn times are only 15 minutes
When I enable spawn points and click on the point it is showing that the live time is only 15 minutes instead of 30 or 60.

### PR DESCRIPTION
**Pull request by Falaris01**
Tested on my local Alternate-Monocle Map, all spawnpointtimer are accurate for my neighbourhood.

Not sure how RocketMap defines a 60 minute spawn but it should default to 30 Minute spawns which is an improvement anyway.

Should fix #38 

image

image

### CODE REVIEW

**Comment by Glennmen** [comment]
Spawn point timers have always been a big question mark for me... 
Or spawn point timers even useful for people? Wouldn't it be better if we remove that and only show spawn point locations.

**Comment by Falaris01** [comment]
They are definitely useful to SOME people. It's a nice-to-have thing I guess.

There are not many people using them tho.

**Comment by Falaris01** [comment]
Works for both Monocle and RM now.
image
On the left Monocle/Alt timers, on the right RM/default

**Comment by hammydown4325** [comment]
Tested this last night and seems to be working perfectly.

**Pull request merged**
