### PR TITLE
Support for 'Message of the Day'

### PR DESCRIPTION
**Pull request by CalamityJames**
Uses the default jQuery UI dialog.

Adds 2 new config parameters, `$motdTitle` and `$motdContent`.

`$motdContent` supports HTML as it's added to `index.php`.

Added checks to `map.common.php` to see if both variables are set and if they are, launches the MOTD.

### CODE REVIEW

**Comment by CalamityJames** [comment]
On my test environment, the index page is quite aggressively cached, so after a bit of thought I wondered if this may be better achieved via an AJAX request as opposed to injecting the message into the index page.

**Comment by Glennmen** [comment]
> On my test environment, the index page is quite aggressively cached, so after a bit of thought I wondered if this may be better achieved via an AJAX request as opposed to injecting the message into the index page.

Good point, maybe we need to think this a little better before we merge it. But I like the feature!

**Comment by bbdoc** [comment]
I love the idea as well, but if I understand it well, this message would be seen once by user and then dismissed. Would be nice to also have the possibility to add a message with a timeframe, e.g. you know you will have an outage and your map will not scan between 8am and 12am, you could push a persistent message for it directly on the map.

**Comment by CalamityJames** [comment]
@bbdoc Actually, it would appear on every load in its current iteration. I thought about adding an `isDismissed` flag in the browser storage but realised if you changed the message you'd need to have a way to clear that flag too. Definitely more thought needed on this, and maybe a timeframe alert too as I know a few people who only scan at certain times

**Comment by CalamityJames** [comment]
Not quite sure what I did with that last commit. Not using PhpStorm to merge again, I'll do it via cmd line next time!

**Comment by CalamityJames** [comment]
MOTD is now called via AJAX with caching disabled to ensure the freshest MOTD for your users!

One potential breaking change: It uses `motd_data` which I've added to `.htaccess` however nginx users will need to get the new rewrite out of the `nginx.example.conf` file and apply it to their config.

**Comment by Glennmen** [comment]
Great! I will test it later and if working well I will merge it.
Good that you decided to go to AJAX ;)

**Pull request merged**
