### PR TITLE
Add a new list on Navbar for multiple locations

### PR DESCRIPTION
**Pull request by edemir-matcomp**
Just add a list of locations on our navbar xD
Too simple, but useful for multiple instances
nav_loc

### CODE REVIEW

**Review by Glennmen — CHANGES_REQUESTED** [review]
Could you also include $location in config/default.php so that the map won't crash when people update. 

And not sure if it should be the first in options nav, but that is personal opinion I guess.

**Comment by edemir-matcomp** [comment]
A better arrangement can be reconsidered in the future =]
We are always open to suggestions xD

**Comment by RaizeTheLimit** [comment]
Just an idea to give more options, but may people share a database through many instances, and I think it would be great to have the map recenter instead of refreshing the page.  A function to centermap and reset zoom (Possibly add zoom to list would be great)

**Comment by Glennmen** [comment]
I would like to see these changes before it can be merged:

- Use preindex.php instead of the old index.php
- Don't place locations first in nav menu
- Instead of reloading map, use JS to move the map to the coords

**Comment by Glennmen** [comment]
I am closing this PR because PR #75 has the same feature but uses JS to move map center instead of reload the page.

**Pull request closed without merging**
