### PR TITLE
Fix mobile notifications on mobile chrome

### PR DESCRIPTION
**Pull request by hammydown4325**
This fix is working for me now so need others to test it as well.

### CODE REVIEW

**Comment by Falaris01** [comment]
Can't get this to work on my setup currently, already informed iroken about it :)

**Comment by hammydown4325** [comment]
I'm working on more fixes for this so bare with me.

**Comment by hammydown4325** [comment]
I have also added a rewrite rule into this for the mobile notifications to work properly.

NGINX
`rewrite ^/serviceWorker.min.js$ /static/dist/js/serviceWorker.min.js last;`

APACHE
`RewriteRule ^serviceWorker.min.js$ static/dist/js/serviceWorker.min.js?$1 [QSA,L]`

I have had confirmed reports from several people right now that this is now fixed but need more testers.

**Comment by Glennmen** [comment]
Did some testing

Android 8.0.0:
- Chrome: OK
- Firefox: OK

iOS 11: (https://blog.izooto.com/ios-push-notifications-safari/)
- Safari: Not working
- Chrome: Not working

macOS High Sierra:
- Chrome: OK
- Safari: OK

**Pull request merged**
