### PR TITLE
Add timers under Pokemon

### PR DESCRIPTION
**Pull request by M4d40**
This PR adds timers under the pokemon icons in the map.

This is a Port of the RocketMap PR by kevdotcom.

You can turn the timers on/off inside the UI (in "Marker Settings")

timers

### CODE REVIEW

**Comment by h0us3cat** [comment]
pls check travis 👍

**Comment by Glennmen** [comment]
After fixing travis errors I will look into this.

**Comment by phonezawphyo** [comment]
Be careful with this. It would greatly slow down the map. Not recommended to show timers as default.

**Comment by MonkeyTedBaker** [comment]
Be careful with this. It would greatly slow down the map. Not recommended to show timers as default.

**Comment by thomasfa18** [comment]
This should be closed, have updated code for dev branch and is now PR91
https://github.com/Glennmen/PMSF/pull/91

**Comment by M4d40** [comment]
Closed because @thomasfa18 continued and finished the PR in his https://github.com/Glennmen/PMSF/pull/91

**Pull request closed without merging**
