### PR TITLE
Split out forks into their own classes

### PR DESCRIPTION
**Pull request by CalamityJames**
Large rework of the way forks are handled, splitting out into their own classes.

This makes adding support for an extra fork **much** easier.

I have also converted #26 to work with the new class system, thanks go to @wateredstorm for his work on that :)

Forks tested:
- [x] Asner Monocle fork
- [x] Monkey Monocle fork
- [x] Sloppy RocketMap fork
- [x] Vanilla Monocle
- [x] Vanilla RocketMap

I am open to any suggestions or improvements for how we handle new classes, at the moment they are all loaded in an array in `config/default.php`

I have also merged in #13 to here, as it saves having multiple PRs open from me!

### CODE REVIEW

**Comment by baskettcase** [comment]
I don't know if you'll want this, but this is a lib file for Asner's Monocle PR, not his fork.
[Monocle_Asner.php.zip](https://github.com/Glennmen/PMSF/files/1293560/Monocle_Asner.php.zip)

Maybe this isn't Asner.. but it's for this Monocle PR: https://github.com/Noctem/Monocle/pull/306

**Comment by beloware** [comment]
Now setup, yet monkey fork.

**Comment by ecology99** [comment]
With this new PR, with RM default I always get this error:
https://prntscr.com/gk0eqk

**Review by cptmedic — CHANGES_REQUESTED** [review]
Sorry for being picky, but for consistency (and because I know someone will eventually ask) in  config.example.php from ```// default/asner/sloppy``` to ```// default/asner/sloppy/monkey```

**Comment by CalamityJames** [comment]
@captainmedic Done, thanks for the suggestion!

**Comment by tobias86aa** [comment]
Sloppys fork seems to be working good.

**Comment by Demokdawa** [comment]
Works perfectly well with lastest commit :p

**Review by cptmedic — APPROVED** [review]

**Comment by cptmedic** [comment]
Monkey branch works on CentOS 7. I have not test the discord include button as the discord is private, but everything else that I use is confirmed working on my instances

**Pull request merged**
